on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: facilebio/facilebio_base_extra
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      CI: true
      TZ: America/Los_Angeles

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      # pandoc is already installed in the docker container
      # - uses: r-lib/actions/setup-pandoc@master
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
