on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: facilebio/facilebio_base_extra
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      CI: true
      TZ: America/Los_Angeles

    steps:
      - uses: actions/checkout@v2
      # The container already has the R version we want, so this will be a
      # no-op, but we like the colorizing/problemMatchrers.r-lib
      #   see r-lib/actions/setup-r/installer.ts acquireR, where
      #   if (returnCode != 0) { ... }
      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
